version: '3.8'

services:
  db:
    image: postgres:13.14-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - ${PATH_VOLUME_PG}:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"  
    depends_on:
      - db




